### ISSUE TITLE
make plots ok

### ISSUE THREAD

**Issue by SamLau95** [SamLau95/pandas_tutor#11]
this breaks:

```python
import pandas as pd
# write python code here, your last line should be a pandas expression
df = pd.DataFrame([('Liam', 'M', 19659, 2020), ('Noah', 'M', 18252, 2020),
                   ('Oliver', 'M', 14147, 2020), ('Elijah', 'M', 13034, 2020),
                   ('William', 'M', 12541, 2020), ('Emma', 'F', 15581, 2020),
                   ('Ava', 'F', 13084, 2020), ('Charlotte', 'F', 13003, 2020),
                   ('Sophia', 'F', 12976, 2020), ('Amelia', 'F', 12704, 2020)],
                  columns=['Name', 'Sex', 'Count', 'Year'])

(df[(df['Count'] > 14000) & (df['Sex'] == 'M')]
.sort_values('Count')
.plot('Count')
)
```

```
Traceback (most recent call last):
  File "/Users/sam/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sam/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/main.py", line 59, in <module>
    print(spec_fn(code))
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/main.py", line 27, in make_tutor_spec
    spec = serialize_to_json(eval_results)
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/serialize.py", line 25, in serialize_to_json
    diagrams = serialize(results)
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/serialize.py", line 19, in serialize
    return [
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/serialize.py", line 20, in <listcomp>
    serialize_one_step(before, after) for before, after in pairs(results)
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/serialize.py", line 36, in serialize_one_step
    rhs=make_df_spec(after.df),
  File "/Users/sam/repos/pandas_tutor/pandas_tutor/serialize.py", line 46, in make_df_spec
    return DFSpec(col_names=df.columns.tolist(),
AttributeError: 'AxesSubplot' object has no attribute 'columns'
```

**Comment by SamLau95** [comment]
closed by #31
